Repository FRONTENDSCHOOL5/final-20-BebeMarket, pull requests merged in 2023-07, with the labels that each got.

#138 💄 Style : 프로필사진 가운데로 정렬
  src/pages/profile/Profile.style.js
Labels: style

#149 이미지 최적화
  src/pages/home/Home.jsx
  src/pages/join/JoinProfile.jsx
  src/pages/uploadPost/UploadPost.jsx
Labels: refactor

#150 이미지 lazyloading 성능개선중
  src/components/common/home/HomePost.jsx
Labels: refactor

#158 :bulb:Docs : map 주석 추가 #155
  src/components/mapInfo/PreschoolList.jsx
  src/components/mapInfo/PreschoolMap.jsx
  src/pages/map/Map.jsx
Labels: modify
